### ISSUE TITLE
i need your help

### ISSUE THREAD

**Issue by unkn0wn-wifi** [bruvv/pineapple-firmware-builder#102]
please do not close this thread and sorry for putting this in the issue tab im new ti github and couldnt find anywhere else to contact you.

my name is sanjai and im a cyber security student in the UK. i have a youtube channel (youtube.com/c/blankdot1) and i make videos on gadgets and all sorts related to ethical hacking.
I have a cool project in mind and that requires your help. I want to build a pineapple style router based on the pi 3 (plenty of power) as a pineapple tetra costs around $200 and thats quite alot. i want to build this opportunity so that all of us that are interested can make this as i want all of this to be open source. I have done a rough sketch down below (its not the neatest but will do for the time being) and it has the design on it. The input needed by you is the actual software side. i want you guys to dev an image that has an openwrt based software that is similar to the pineapple as that is quite user friendly. Again this is if you can. 

kingsnakeyt1@gmail.com

please contact me for more information as this would be amazing

waiting to hear from you,

from,
sanjai

![unnamed](https://user-images.githubusercontent.com/70666455/92213019-c7034800-ee8a-11ea-9687-568d75c8f651.png)

**Comment by bruvv** [comment]
Hardware is a complete mismatch and it will not work. Sorry.

**Comment by unkn0wn-wifi** [comment]
Oh no problem that is fine. But I downloaded your firmware for the
pineapple and what I found that when I tried Internet sharing on my kali
machine it just said detecting and then when it does connect rarely it says
"invalid argument " and Internet sharing dont work. Please help
